<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `ecs_admin_user`;");
E_C("CREATE TABLE `ecs_admin_user` (
  `user_id` smallint(5) unsigned NOT NULL auto_increment,
  `user_name` varchar(60) NOT NULL default '',
  `email` varchar(60) NOT NULL default '',
  `password` varchar(32) NOT NULL default '',
  `ec_salt` varchar(10) default NULL,
  `add_time` int(11) NOT NULL default '0',
  `last_login` int(11) NOT NULL default '0',
  `last_ip` varchar(15) NOT NULL default '',
  `action_list` text NOT NULL,
  `nav_list` text NOT NULL,
  `lang_type` varchar(50) NOT NULL default '',
  `agency_id` smallint(5) unsigned NOT NULL,
  `suppliers_id` smallint(5) unsigned default '0',
  `todolist` longtext,
  `role_id` smallint(5) default NULL,
  `seller_id` int(11) NOT NULL default '0' COMMENT '入驻商家ID',
  PRIMARY KEY  (`user_id`),
  KEY `user_name` (`user_name`),
  KEY `agency_id` (`agency_id`)
) ENGINE=MyISAM AUTO_INCREMENT=20 DEFAULT CHARSET=utf8");
E_D("replace into `ecs_admin_user` values('1','admin','admin@admin.com','2b9a70d085b10cd8c61378f5c45ee189','1978','1398244330','1431715980','127.0.0.1','all','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list,会员列表|users.php?act=list,商店设置|shop_config.php?act=list_edit','','0','0','ACE','0','0');");
E_D("replace into `ecs_admin_user` values('2','bjgonghuo1','bj@163.com','d0c015b6eb9a280f318a4c0510581e7e','','1245044099','0','','delivery_view,back_view','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list,会员列表|users.php?act=list,商店设置|shop_config.php?act=list_edit','','0','0','','0','0');");
E_D("replace into `ecs_admin_user` values('5','xiaowang','984265135@qq.com','2b9a70d085b10cd8c61378f5c45ee189','1978','1409179712','1420660461','116.231.89.154','goods_manage,remove_back,goods_auto,picture_batch,goods_export,goods_batch,order_os_edit,order_ps_edit,order_ss_edit,order_view,order_view_finished,sale_order_stats,booking,delivery_view,back_view,sale_order_stats','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list','','0','0','','0','2');");
E_D("replace into `ecs_admin_user` values('6','yangcheng01','3096452189@qq.com','e380056567d7422c10231038d4765723','1806','1416510382','1416848159','124.164.69.238','goods_manage,remove_back,cat_manage,cat_drop,attr_manage,brand_manage,comment_priv,tag_manage,goods_type,goods_auto,virualcard,picture_batch,goods_export,goods_batch,gen_goods_script,sale_notice,notice_logs,article_cat,article_manage,shopinfo_manage,shophelp_manage,vote_priv,article_auto,feedback_priv,integrate_users,sync_users,users_manage,users_drop,user_rank,surplus_manage,account_manage,baitiao_manage,template_manage,admin_manage,admin_drop,allot_priv,logs_manage,logs_drop,agency_manage,suppliers_manage,role_manage,shop_config,ship_manage,payment,shiparea_manage,area_manage,friendlink,db_backup,db_renew,flash_manage,navigator,cron,affiliate,affiliate_ck,sitemap,file_priv,file_check,reg_fields,shop_authorized,webcollect_manage,order_os_edit,order_ps_edit,order_ss_edit,order_edit,order_view,order_view_finished,repay_manage,booking,sale_order_stats,client_flow_stats,delivery_view,back_view,topic_manage,snatch_manage,ad_manage,gift_manage,card_manage,pack,bonus_manage,auction,group_by,favourable,whole_sale,package_manage,exchange_goods,attention_list,email_list,magazine_list,view_sendlist,template_select,template_setup,library_manage,lang_edit,backup_setting,mail_template,db_backup,db_renew,db_optimize,sql_query,convert,sms_send,seller_fields,seller_list,seller_yj_manage,store_cate_manage,store_manege,street_tags_manege','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list,会员列表|users.php?act=list,商店设置|shop_config.php?act=list_edit','','0','0','','0','0');");
E_D("replace into `ecs_admin_user` values('7','yangcheng02','3037018468@qq.com','b45342d38fbc6540cc2e6ddf6c0d85ef','2040','1416510483','1416519949','118.76.98.164','goods_manage,remove_back,cat_manage,cat_drop,attr_manage,brand_manage,comment_priv,tag_manage,goods_type,goods_auto,virualcard,picture_batch,goods_export,goods_batch,gen_goods_script,sale_notice,notice_logs,article_cat,article_manage,shopinfo_manage,shophelp_manage,vote_priv,article_auto,feedback_priv,integrate_users,sync_users,users_manage,users_drop,user_rank,surplus_manage,account_manage,baitiao_manage,template_manage,admin_manage,admin_drop,allot_priv,logs_manage,logs_drop,agency_manage,suppliers_manage,role_manage,shop_config,ship_manage,payment,shiparea_manage,area_manage,friendlink,db_backup,db_renew,flash_manage,navigator,cron,affiliate,affiliate_ck,sitemap,file_priv,file_check,reg_fields,shop_authorized,webcollect_manage,order_os_edit,order_ps_edit,order_ss_edit,order_edit,order_view,order_view_finished,repay_manage,booking,sale_order_stats,client_flow_stats,delivery_view,back_view,topic_manage,snatch_manage,ad_manage,gift_manage,card_manage,pack,bonus_manage,auction,group_by,favourable,whole_sale,package_manage,exchange_goods,attention_list,email_list,magazine_list,view_sendlist,template_select,template_setup,library_manage,lang_edit,backup_setting,mail_template,db_backup,db_renew,db_optimize,sql_query,convert,sms_send,seller_fields,seller_list,seller_yj_manage,store_cate_manage,store_manege,street_tags_manege','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list,会员列表|users.php?act=list,商店设置|shop_config.php?act=list_edit','','0','0','','0','0');");
E_D("replace into `ecs_admin_user` values('8','yangcheng03','3032826104@qq.com','afe64bf2e155af6798ea7fed8323d719','8670','1416510580','1416520172','118.76.98.164','goods_manage,remove_back,cat_manage,cat_drop,attr_manage,brand_manage,comment_priv,tag_manage,goods_type,goods_auto,virualcard,picture_batch,goods_export,goods_batch,gen_goods_script,sale_notice,notice_logs,article_cat,article_manage,shopinfo_manage,shophelp_manage,vote_priv,article_auto,feedback_priv,integrate_users,sync_users,users_manage,users_drop,user_rank,surplus_manage,account_manage,baitiao_manage,template_manage,admin_manage,admin_drop,allot_priv,logs_manage,logs_drop,agency_manage,suppliers_manage,role_manage,shop_config,ship_manage,payment,shiparea_manage,area_manage,friendlink,db_backup,db_renew,flash_manage,navigator,cron,affiliate,affiliate_ck,sitemap,file_priv,file_check,reg_fields,shop_authorized,webcollect_manage,order_os_edit,order_ps_edit,order_ss_edit,order_edit,order_view,order_view_finished,repay_manage,booking,sale_order_stats,client_flow_stats,delivery_view,back_view,topic_manage,snatch_manage,ad_manage,gift_manage,card_manage,pack,bonus_manage,auction,group_by,favourable,whole_sale,package_manage,exchange_goods,attention_list,email_list,magazine_list,view_sendlist,template_select,template_setup,library_manage,lang_edit,backup_setting,mail_template,db_backup,db_renew,db_optimize,sql_query,convert,sms_send,seller_fields,seller_list,seller_yj_manage,store_cate_manage,store_manege,street_tags_manege','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list,会员列表|users.php?act=list,商店设置|shop_config.php?act=list_edit','','0','0','','0','0');");
E_D("replace into `ecs_admin_user` values('9','yangcheng04','3080128204@qq.com','939ad85fdc7f917130c8ead1e3e11551','995','1416510658','1416520010','118.76.98.164','goods_manage,remove_back,cat_manage,cat_drop,attr_manage,brand_manage,comment_priv,tag_manage,goods_type,goods_auto,virualcard,picture_batch,goods_export,goods_batch,gen_goods_script,sale_notice,notice_logs,article_cat,article_manage,shopinfo_manage,shophelp_manage,vote_priv,article_auto,feedback_priv,integrate_users,sync_users,users_manage,users_drop,user_rank,surplus_manage,account_manage,baitiao_manage,template_manage,admin_manage,admin_drop,allot_priv,logs_manage,logs_drop,agency_manage,suppliers_manage,role_manage,shop_config,ship_manage,payment,shiparea_manage,area_manage,friendlink,db_backup,db_renew,flash_manage,navigator,cron,affiliate,affiliate_ck,sitemap,file_priv,file_check,reg_fields,shop_authorized,webcollect_manage,order_os_edit,order_ps_edit,order_ss_edit,order_edit,order_view,order_view_finished,repay_manage,booking,sale_order_stats,client_flow_stats,delivery_view,back_view,topic_manage,snatch_manage,ad_manage,gift_manage,card_manage,pack,bonus_manage,auction,group_by,favourable,whole_sale,package_manage,exchange_goods,attention_list,email_list,magazine_list,view_sendlist,template_select,template_setup,library_manage,lang_edit,backup_setting,mail_template,db_backup,db_renew,db_optimize,sql_query,convert,sms_send,seller_fields,seller_list,seller_yj_manage,store_cate_manage,store_manege,street_tags_manege','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list,会员列表|users.php?act=list,商店设置|shop_config.php?act=list_edit','','0','0','','0','0');");
E_D("replace into `ecs_admin_user` values('10','yangcheng05','2763299131@qq.com','8c4f0157856aecb229094679973ce4a0','9327','1416510730','1416866717','124.164.69.238','goods_manage,remove_back,cat_manage,cat_drop,attr_manage,brand_manage,comment_priv,tag_manage,goods_type,goods_auto,virualcard,picture_batch,goods_export,goods_batch,gen_goods_script,sale_notice,notice_logs,article_cat,article_manage,shopinfo_manage,shophelp_manage,vote_priv,article_auto,feedback_priv,integrate_users,sync_users,users_manage,users_drop,user_rank,surplus_manage,account_manage,baitiao_manage,order_os_edit,order_ps_edit,order_ss_edit,order_edit,order_view,order_view_finished,repay_manage,booking,sale_order_stats,client_flow_stats,delivery_view,back_view,topic_manage,snatch_manage,ad_manage,gift_manage,card_manage,pack,bonus_manage,auction,group_by,favourable,whole_sale,package_manage,exchange_goods,attention_list,email_list,magazine_list,view_sendlist,sms_send,seller_fields,seller_list,seller_yj_manage,store_cate_manage,store_manege,street_tags_manege','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list,会员列表|users.php?act=list,商店设置|shop_config.php?act=list_edit','','0','0','','0','0');");
E_D("replace into `ecs_admin_user` values('11','ljr','ljr@qq.com','f822c903f8d3ed6390ef5f2334d951ae','','1417042223','0','','','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list,会员列表|users.php?act=list,商店设置|shop_config.php?act=list_edit','','0','0','','0','0');");
E_D("replace into `ecs_admin_user` values('12','测试','1038422306@qq.com','bbea2c47808d271f4d97c650b760d336','5857','1418236921','1418248126','211.147.235.213','delivery_view,back_view','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list','','0','3','','0','3');");
E_D("replace into `ecs_admin_user` values('13','wwwbbbb','1035489562@qq.com','e10adc3949ba59abbe56e057f20f883e','','1418239248','0','','delivery_view,back_view','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list','','0','4','','0','4');");
E_D("replace into `ecs_admin_user` values('14','admin123456','www_bbbb@163.com','0d4f7e6712aacabd0fa10e9e7e713afd','382','1419191875','1419207289','14.145.50.112','goods_manage,remove_back,cat_manage,cat_drop,attr_manage,brand_manage,comment_priv,tag_manage,goods_type,goods_auto,virualcard,picture_batch,goods_export,goods_batch,gen_goods_script,sale_notice,notice_logs,article_cat,article_manage,shopinfo_manage,shophelp_manage,vote_priv,article_auto,feedback_priv,integrate_users,sync_users,users_manage,users_drop,user_rank,surplus_manage,account_manage,baitiao_manage,template_manage,admin_manage,admin_drop,allot_priv,logs_manage,logs_drop,agency_manage,suppliers_manage,role_manage,shop_config,ship_manage,payment,shiparea_manage,area_manage,friendlink,db_backup,db_renew,flash_manage,navigator,cron,affiliate,affiliate_ck,sitemap,file_priv,file_check,reg_fields,shop_authorized,webcollect_manage,order_os_edit,order_ps_edit,order_ss_edit,order_edit,order_view,order_view_finished,repay_manage,booking,sale_order_stats,client_flow_stats,delivery_view,back_view,topic_manage,snatch_manage,ad_manage,gift_manage,card_manage,pack,bonus_manage,auction,group_by,favourable,whole_sale,package_manage,exchange_goods,attention_list,email_list,magazine_list,view_sendlist,template_select,template_setup,library_manage,lang_edit,backup_setting,mail_template,db_backup,db_renew,db_optimize,sql_query,convert,sms_send,seller_fields,seller_list,seller_yj_manage,store_cate_manage,store_manege,street_tags_manege','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list','','0','0','','0','5');");
E_D("replace into `ecs_admin_user` values('15','ACE','985372616@qq.com','2eee1a5cbdf2f566d0dd61a3700995a2','369','1419369198','1419379630','14.145.48.246','goods_manage,remove_back,goods_auto,picture_batch,goods_export,goods_batch,order_os_edit,order_ps_edit,order_ss_edit,order_view,order_view_finished,sale_order_stats,booking,delivery_view,back_view,sale_order_stats','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list','','0','0','','0','6');");
E_D("replace into `ecs_admin_user` values('16','liushengzhong','931510304@qq.com','e074858133feb2ad56570d524f2b0485','5480','1419371456','1419375050','14.145.48.246','goods_manage,remove_back,goods_auto,picture_batch,goods_export,goods_batch,order_os_edit,order_ps_edit,order_ss_edit,order_view,order_view_finished,sale_order_stats,booking,delivery_view,back_view,sale_order_stats','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list','','0','0','','0','7');");
E_D("replace into `ecs_admin_user` values('17','无梧桐','2991152301@qq.com','eacbb3b9dbc026588461ef287675d094','9365','1419373791','1419383954','14.145.48.246','goods_manage,remove_back,goods_auto,picture_batch,goods_export,goods_batch,order_os_edit,order_ps_edit,order_ss_edit,order_view,order_view_finished,sale_order_stats,booking,delivery_view,back_view,sale_order_stats','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list','','0','1','','0','8');");
E_D("replace into `ecs_admin_user` values('18','888','123@qq.com','a3a51be7fe19489dfc19ac2f564625a1','6542','1419375146','1419375170','14.145.48.246','goods_manage,remove_back,goods_auto,picture_batch,goods_export,goods_batch,order_os_edit,order_ps_edit,order_ss_edit,order_view,order_view_finished,sale_order_stats,booking,delivery_view,back_view,sale_order_stats','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list','','0','0','','0','9');");
E_D("replace into `ecs_admin_user` values('19','777','777777@qq.com','4cc48f83d3a73f3bf5e57fd0924140a6','9152','1419380833','1419381175','14.145.48.246','goods_manage,remove_back,goods_auto,picture_batch,goods_export,goods_batch,order_os_edit,order_ps_edit,order_ss_edit,order_view,order_view_finished,sale_order_stats,booking,delivery_view,back_view,sale_order_stats','商品列表|goods.php?act=list,订单列表|order.php?act=list,用户评论|comment_manage.php?act=list','','0','0','','0','10');");

require("../../inc/footer.php");
?>